general:
  data_path: ../data/
  model_name: lcw99/t5-base-korean-text-summary
  output_dir: ./
inference:
  batch_size: 16
  ckt_path: model ckt path
  early_stopping: true
  generate_max_length: 100 # 200
  no_repeat_ngram_size: 2
  num_beams: 4
  remove_tokens:
  - <usr>
  - <s>
  - </s>
  - <pad>
  result_path: ./prediction/
tokenizer:
  bos_token: <s>
  decoder_max_len: 100
  encoder_max_len: 512
  eos_token: </s>
  special_tokens:
  - '#Person1#'
  - '#Person2#'
  - '#Person3#'
  - '#PhoneNumber#'
  - '#Address#'
  - '#PassportNumber#'
  - '#DateOfBirth#'
  - '#SSN#'
  - '#CardNumber#'
  - '#CarNumber#'
  - '#Email#'
  - '#Person#'
  - '#Person4#'
  - '#Person5#'
  - '#Person6#'
  - '#Person7#'
training:
  do_eval: true
  do_train: true
  early_stopping_patience: 3
  early_stopping_threshold: 0.001
  evaluation_strategy: epoch
  fp16: true
  generation_max_length: 100
  gradient_accumulation_steps: 1 # 4
  learning_rate: 1.0e-05
  load_best_model_at_end: true
  logging_dir: ./logs
  logging_strategy: epoch
  lr_scheduler_type: cosine
  num_train_epochs: 10
  optim: adamw_torch
  overwrite_output_dir: true
  per_device_eval_batch_size: 1
  per_device_train_batch_size: 1
  predict_with_generate: true
  report_to: wandb
  save_strategy: epoch
  save_total_limit: 5
  seed: 42
  warmup_ratio: 0.1
  weight_decay: 0.01
wandb:
  entity: seongmyeonggi
  name: noahkim/KoT5_news_summarization 
  project: summarizaion(T5)
