general:
  data_path: ../data/
  model_name: EbanLee/kobart-summary-v3
  output_dir: ./
inference:
  batch_size: 32
  ckt_path: model ckt path
  early_stopping: true
  generate_max_length: 250  # 증가
  no_repeat_ngram_size: 3  # 증가
  num_beams: 5  # 증가
  remove_tokens:
  - <usr>
  - <s>
  - </s>
  - <pad>
  result_path: ./prediction/
tokenizer:
  bos_token: <s>
  decoder_max_len: 250  # 증가
  encoder_max_len: 1024
  eos_token: </s>
  special_tokens:
  - '#Person1#'
  - '#Person2#'
  - '#Person3#'
  - '#Person4#'
  - '#Person5#'
  - '#Person6#'
  - '#Person7#'
  - '#PhoneNumber#'
  - '#Address#'
  - '#PassportNumber#'
  - '#DateOfBirth#'
  - '#SSN#'
  - '#CardNumber#'
  - '#CarNumber#'
  - '#Email#'
training:
  do_eval: true
  do_train: true
  early_stopping_patience: 5  # 증가
  early_stopping_threshold: 0.0005  # 감소
  evaluation_strategy: steps  # 변경
  fp16: true
  generation_max_length: 250  # 증가
  gradient_accumulation_steps: 8  # 증가
  learning_rate: 1.0e-05
  load_best_model_at_end: true
  logging_dir: ./logs
  logging_steps: 50  # 감소
  logging_strategy: steps  # 변경
  lr_scheduler_type: linear  # 변경
  num_train_epochs: 30  # 증가
  optim: adamw_torch
  overwrite_output_dir: true
  per_device_eval_batch_size: 16
  per_device_train_batch_size: 16
  predict_with_generate: true
  report_to: wandb
  save_strategy: steps  # 변경
  save_steps: 500  # 추가
  save_total_limit: 3  # 감소
  seed: 42
  warmup_ratio: 0.2  # 증가
  weight_decay: 0.05  # 증가
wandb:
  entity: seongmyeonggi
  name: kobart-summary-v3(linear)
  project: summarization
